### ISSUE TITLE
Letrec Parser.

### ISSUE THREAD

**Issue by vanh17** [vanh17/SnoopCH#23] opened 2016-04-16 20:27 UTC
So I use the same syntax for let and let_, however I really dont know why it does not let me compile. It raise parser error.
I use the same syntax, and let, let_ work, but letrec does not. Could you please have a look on my parser file to see where the mistake comes from?
Thank you so much Dr. @skiadas 
Warmest,
Hoang

**Comment by skiadas** [comment] 2016-04-16 20:36
You'll have to be a whole lot more specific about precisely what error you are getting. "it's not working" is not a valid question. What did you type that gives you a parser error? What should one do to reproduce the error?

**Comment by vanh17** [comment] 2016-04-16 20:40
So I typed
(letrec ([x (lambda (n) (y n))] [y (lambda (n) (+ n 3))]) (x 3));;
however it raised a parser error.
Then I tried to break the the typing a little bit
(letrec ([ and hit enter, but it stop me from typing more after this point and give me a parser error.

**Comment by skiadas** [comment] 2016-04-16 20:45
I cannot reproduce your problem. On my end letrec works fine and your example above gives 6. Are you sure you have recompiled properly, and what you have committed is what you have locally?

**Comment by vanh17** [comment] 2016-04-16 20:50
Yes, I  think so, I have a feeling that it would work on Linux but not on windows, cant believe it was actually a case. I compiled normally like what I have done so far so there would be no mistake about it.

**Comment by vanh17** [comment] 2016-04-16 20:51
Oh, never mind, I think I somehow typed the wrong name for snoopch.exe. it is now work. Thank you so much Dr. @skiadas 
Warmest,

**Closed as completed** 2016-04-16 21:06 UTC
Labels: implementation
